name: sbc-turingrk1

on:
  push:
    branches: [ 'main', 'release-*' ]
    tags:
      - "v*"

jobs:
  sbc:
    runs-on: buildjet-16vcpu-ubuntu-2204-arm

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push sbc turingrk1 overlay image
        run: make
        env:
          PUSH: '1'
          USERNAME: ${{ github.actor }}
          PROGRESS: plain
          CI_ARGS: "--cache-from=ghcr.io/${{ github.actor }}/sbc-turingrk1:cache --cache-to=ghcr.io/${{ github.actor }}/sbc-turingrk1:cache"

      - name: Create Talos image and installer
        run: |
          curl -sL "https://github.com/google/go-containerregistry/releases/download/v0.19.1/go-containerregistry_Linux_arm64.tar.gz" | tar -zxv -C /usr/local/bin/ crane
          IMAGETAG=$(git describe --tag --always --dirty --match v[0-9]\*)
          docker run -v $(pwd)/_out:/out --rm -t  ghcr.io/siderolabs/imager:v1.7.0 installer --arch arm64 --overlay-image ghcr.io/nberlee/sbc-turingrk1:$IMAGETAG --overlay-name=turingrk1
          crane push _out/installer-arm64.tar ghcr.io/nberlee/installer:$IMAGETAG
          docker run -v $(pwd)/_out:/out -v /dev:/dev --privileged --rm -t ghcr.io/siderolabs/imager:v1.7.0 metal --arch arm64 --overlay-image ghcr.io/nberlee/sbc-turingrk1:$IMAGETAG --overlay-name=turingrk1

      - uses: actions/upload-artifact@v3
        with:
          name: image-turing-rk1
          path: _out/*.raw.xz
          if-no-files-found: error
