name: sbc-turingrk1

on:
  push:
    branches: [ 'main', 'release-*' ]
    tags:
      - "v*"

jobs:
  sbc:
    runs-on: buildjet-16vcpu-ubuntu-2204-arm

    permissions:
      contents: read
      packages: write


    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true

      - name: Build and push sbc turingrk1 overlay image
        run: make
        env:
          PUSH: '1'
          USERNAME: ${{ github.actor }}
          #PLATFORM: linux/arm64
          PROGRESS: plain
          CI_ARGS: "--cache-from=ghcr.io/${{ github.actor }}/sbc-turingrk1:cache --cache-to=ghcr.io/${{ github.actor }}/sbc-turingrk1:cache"
